basic:
  filepath: "/mnt/disk/files/gar_xml"
  prefix: "all"
db:
  driver: "mysql"
  username: "genesis"
  password: "N2s3I8g7"
  host: "192.168.0.99"
  port: "3306"
  dbname: "fias"
  sslmode: "disable"

SFTP:
  host: 192.168.0.99
  username: web
  password: np6aGzq5
  port: 22

# В поле driver писать или "postgres" или "mysql"
tablename:
  dict:
    ParamTypes: "dict_paramtypes"
    NDocTypes: "dict_doctypes"
    NDockInds: "dict_doctkinds"
    AddHouseTypes: "dict_addhousetypes"
    AddressObjectTypes: "dict_addressobjecttypes"
    ApartmentTypes: "dict_apartmenttypes"
    HouseTypes: "dict_housetypes"
    OperationTypes: "dict_operationtypes"
    RoomTypes: "dict_roomtypes"
    LevelsTypes: "dict_levelstypes"
  content:
    AdmHierarchy: "hierarchy_adm"
    MunHierarchy: "hierarchy_mun"
    Apartments: "apartments"
    ApartmentsP: "apartments_param"
    Carplaces: "carplaces"
    CarplacesP: "carplaces_param"
    Houses: "houses"
    HousesP: "houses_param"
    Rooms: "rooms"
    RoomsP: "rooms_param"
    Steads: "steads"
    SteadsP: "steads_param"
    ChangeHistory: "change_history"
    NormDocs: "norm_docs"
    ReestrObject: "reestr_object"
    AddrObject: "object"
    AddrObjectP: "object_param"
    ObjectDivision: "object_division"