db:
  driver: "mysql"
  username: "konstantine"
  password: "23981487"
  host: "localhost"
  port: "6033"
  dbname: "fias2"
  sslmode: "disable"

# В поле driver писать или "postgres" или "mysql"
tablename:
  dict:
    ParamTypes: "dict_paramtypes"
    NDocTypes: "dict_doctypes"
    NDockInds: "dict_doctkinds"
    AddHouseTypes: "dict_addhousetypes"
    AddressObjectTypes: "dict_addressobjecttypes"
    ApartmentTypes: "dict_apartmenttypes"
    HouseTypes: "dict_housetypes"
    OperationTypes: "dict_operationtypes"
    RoomTypes: "dict_roomtypes"
    LevelsTypes: "dict_levelstypes"
  content:
    AdmHierarchy: "hierarchy_adm"
    MunHierarchy: "hierarchy_mun"
    Apartments: "apartments"
    ApartmentsP: "apartments_param"
    Carplaces: "carplaces"
    CarplacesP: "carplaces_param"
    Houses: "houses"
    HousesP: "houses_param"
    Rooms: "rooms"
    RoomsP: "rooms_param"
    Steads: "steads"
    SteadsP: "steads_param"
    ChangeHistory: "change_history"
    NormDocs: "norm_docs"
    ReestrObject: "reestr_object"
    AddrObject: "object"
    AddrObjectP: "object_param"
    ObjectDivision: "object_division"