go get github.com/PuerkitoBio/goquery 
go get github.com/andybalholm/cascadia 
go get github.com/fsnotify/fsnotify 
go get github.com/go-sql-driver/mysql 
go get github.com/hashicorp/hcl 
go get github.com/jmoiron/sqlx 
go get github.com/lib/pq 
go get github.com/magiconair/properties 
go get github.com/mattn/go-runewidth 
go get github.com/mitchellh/mapstructure 
go get github.com/olekukonko/tablewriter 
go get github.com/pelletier/go-toml/v2 
go get github.com/sirupsen/logrus 
go get github.com/spf13/afero 
go get github.com/spf13/cast 
go get github.com/spf13/jwalterweatherman 
go get github.com/spf13/pflag 
go get github.com/spf13/viper 
go get github.com/ssor/bom 
go get github.com/subosito/gotenv 
go get golang.org/x/net 
go get golang.org/x/sys 
go get golang.org/x/text 
go get gopkg.in/ini.v1 
go get gopkg.in/yaml.v3 
go get jaytaylor.com/html2text 